name: cleanarch
description: A new Flutter package project.
version: 0.0.1
author: Luciano Bonifacio Rodrigues
homepage: https://flutuate.io/

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1  # ^0.17.0-nullsafety
  async: ^2.5.0-nullsafety.1
  simply_injector: ^1.0.0-nullsafety.4
  http: ^0.12.2
  #package_info: '>=0.4.3 <2.0.0'
  package_info:
    path: ../plugins/packages/package_info

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_driver:
    #sdk: flutter
  test: ^1.16.0-nullsafety.5
  #integration_test:
    #path: ./test
  pedantic: 1.10.0-nullsafety.2 # ^1.9.0

flutter:
  assets:
    - assets/locale/localization_en_US.json
    - assets/locale/localization_pt_BR.json
    - assets/appsettings.json


#--------------------------------------------------------------------------------------------------------
#
# Testes unitários:
#
#   flutter test --enable-experiment=non-nullable [path]
#
#   dart run --enable-experiment=non-nullable [path]
#
#   dart test --enable-experiment=non-nullable [path]
#
#--------------------------------------------------------------------------------------------------------
#
# Testes de integração:
#
# flutter run --enable-experiment=non-nullable test_driver\...\filename.dart
#
#--------------------------------------------------------------------------------------------------------
#
# Analisar código:
#
# dartanalyzer -v --enable-experiment=non-nullable [path]
#
#--------------------------------------------------------------------------------------------------------
#
# Formatar fontes:
#
# dartfmt -w <path>
#
#--------------------------------------------------------------------------------------------------------
